build:
  version: "2.0"
spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/accounts?serverTimezone=UTC&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ''
accounts:
  message: "Welcome to EazyBank accounts 123454 related local APIs "
  contactDetails:
    name: "Smitha Ray - QAB Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371
